image: gitlab-registry.cern.ch/cms-analysis/general/combine-container:CMSSW_14_1_0_pre4-combine_v10.2.0-harvester_v3.0.0



variables:
  CI_SCRIPTS_PATH: "ci-test/scripts"

before_script:
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - cd /home/cmsusr/CMSSW_14_1_0_pre4/
  - cmsenv || true
  - if test -f ./setup_env.sh; then source setup_env.sh; fi;


stages:
  - workspace
  - card 
  - diagnostic

make_workspace:
  stage: workspace
  tags: [cvmfs]
  script:
    - ./build_workspace.py

make_card:
  stage: card
  tags: [cvmfs]
  script:
    - workspace_tag=`date +%Y_%m_%d`
    - cd monojet/Run3/${workspace_tag}/recoil/
    - make cards

make_diag:
  stage: card
  tags: [cvmfs]
  script:
    - workspace_tag=`date +%Y_%m_%d`
    - cd monojet/Run3/${workspace_tag}/recoil/
    - make diag
    - make plots