image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker/al9-cms

variables:
  LCG_ENV: "/cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-el9-gcc11-opt/"
  CI_SCRIPTS_PATH: "ci-test/scripts"
  CMS_PATH: /cvmfs/cms.cern.ch
  CMSSW_RELEASE: CMSSW_14_1_0_pre4
  SCRAM_ARCH: el9_amd64_gcc12

before_script:
  - df -H ./
  - cat /proc/meminfo
  - source ${LCG_ENV}/setup.sh
  - pwd
  - ls -alh
  - if test -f ./setup_env.sh; then source setup_env.sh; fi;


stages:
  - setup
  - validation


cmssw_compile:
  stage: setup 
  image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker/al9-cms
  tags:
    - cvmfs
  script:
    - set +u && source ${CMS_PATH}/cmsset_default.sh; set -u
    - export SCRAM_ARCH=${SCRAM_ARCH}
    - cmsrel ${CMSSW_RELEASE}
    - cd ${CMSSW_RELEASE}/src
    - cmsenv
    - git clone https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit.git HiggsAnalysis/CombinedLimit
    - cd $CMSSW_BASE/src/HiggsAnalysis/CombinedLimit
    - git fetch origin
    - git checkout v10.0.1
    - scramv1 b clean; scramv1 b 
    - cd $CMSSW_BASE/src
    - git clone https://github.com/cms-analysis/CombineHarvester.git CombineHarvester
    - scram b -j4
